### PR TITLE
Remove package-lock.json in favor of yarn

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

# Summary
- Remove package-lock.json file in favor of yarn and the gitpod integration.

# Review By (Date)
- Feb 28

# Criticality
- Low

# Urgency
- None

# Review Tasks

1. Think about the change and your work. Leave comments.

### CODE REVIEW

**Review by jdwjdwjdw — APPROVED** [review]
Looks good to me. Successfully ran compiler through `yarn`/gitpod and everything appears to be working as expected.

**Comment by imonroe** [comment]
This seems to work fine to me.

**Review by imonroe — APPROVED** [review]
lgtm

**Comment by sherakama** [comment]
Thanks @jdwjdwjdw and @imonroe 

Anyone else? I'm going to put a due date of the 28th on this otherwise it is going to merge.

**Review by joegl — APPROVED** [review]

**Pull request merged**
